name: AI Deployment Suggestion

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ai_suggest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Simulate Test Results
        run: |
          echo "Applied patch to logging; no downtime; all tests passed" > logs.txt

      - name: Send logs + metadata to AI Flask API
        id: suggest
        run: |
          suggestion=$(curl -s -X POST https://33b9-115-112-99-50.ngrok-free.app/suggest \
            -H "Content-Type: application/json" \
            -d '{
              "logs": "Applied patch to logging; no downtime expected.",
              "test_results": {"passed": true},
              "app_type": "api",
              "cost_sensitivity": "high",
              "traffic_pattern": "high",
              "zero_downtime_required": true
            }' | jq -r .suggestion)

          echo "AI_SUGGESTION<<EOF" >> $GITHUB_ENV
          echo "$suggestion" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send Google Chat Notification
        run: |
          curl -X POST "${{ secrets.GCHAT_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "cardsV2": [
                {
                  "card": {
                    "header": {
                      "title": "🚀 AI Deployment Suggestion",
                      "subtitle": "Based on code + test context",
                      "imageUrl": "https://cdn-icons-png.flaticon.com/512/190/190411.png",
                      "imageType": "CIRCLE"
                    },
                    "sections": [
                      {
                        "header": "📌 Recommendation",
                        "collapsible": false,
                        "widgets": [
                          {
                            "textParagraph": {
                              "text": "Based on the logs and test results, I would recommend a <b>rolling update</b> deployment strategy."
                            }
                          }
                        ]
                      },
                      {
                        "header": "📋 Reasoning",
                        "widgets": [
                          {
                            "textParagraph": {
                              "text": "1. The patch was applied with <i>no expected downtime</i>.<br>2. <b>All tests passed</b>, indicating no major issues."
                            }
                          }
                        ]
                      },
                      {
                        "header": "✅ Why Rolling Update",
                        "widgets": [
                          {
                            "textParagraph": {
                              "text": "• Updates instances one by one<br>• Zero downtime for users<br>• Easy rollback if needed"
                            }
                          }
                        ]
                      }
                    ]
                  }
                }
              ]
            }'


