name: AI Deployment Suggestion

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  ai_suggest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Get Git Diff (Latest Commit)
        id: diff
        run: |
          git log -1 --pretty=format:"%h - %s" > commit_info.txt
          git show --pretty="" --name-only > files_changed.txt
          git show > patch.txt

      - name: Send logs + metadata to AI Flask API
        id: suggest
        run: |
<<<<<<< HEAD
          PATCH_CONTENT=$(cat patch.txt | jq -Rs .)
          COMMIT_MSG=$(cat commit_info.txt | jq -Rs .)
          FILES=$(cat files_changed.txt | jq -Rs .)

          suggestion=$(curl -s -X POST https://33b9-115-112-99-50.ngrok-free.app/suggest \
            -H "Content-Type: application/json" \
            -d "{
              \"logs\": $PATCH_CONTENT,
              \"commit_message\": $COMMIT_MSG,
              \"files_changed\": $FILES,
              \"test_results\": {\"passed\": true},
              \"app_type\": \"api\",
              \"cost_sensitivity\": \"high\",
              \"traffic_pattern\": \"high\",
              \"zero_downtime_required\": true
            }" | jq -r .suggestion)
=======
          suggestion=$(curl -s -X POST https://33b9-115-112-99-50.ngrok-free.app/suggest \
            -H "Content-Type: application/json" \
            -d '{
              "logs": "Applied patch to logging; no downtime expected.",
              "test_results": {"passed": true},
              "app_type": "api",
              "cost_sensitivity": "high",
              "traffic_pattern": "high",
              "zero_downtime_required": true
            }' | jq -r .suggestion)
>>>>>>> 95e4d276ba155bbc84c30c3a966784313d49847e

          echo "AI_SUGGESTION<<EOF" >> $GITHUB_ENV
          echo "$suggestion" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Send Google Chat Notification
        run: |
          curl -X POST "${{ secrets.GCHAT_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "cardsV2": [
                {
                  "card": {
                    "header": {
                      "title": "🚀 AI Deployment Suggestion",
<<<<<<< HEAD
                      "subtitle": "Based on latest code commit",
=======
                      "subtitle": "Based on code + test context",
>>>>>>> 95e4d276ba155bbc84c30c3a966784313d49847e
                      "imageUrl": "https://cdn-icons-png.flaticon.com/512/190/190411.png",
                      "imageType": "CIRCLE"
                    },
                    "sections": [
                      {
                        "header": "📌 Recommendation",
<<<<<<< HEAD
                        "widgets": [
                          {
                            "textParagraph": {
                              "text": "'"${{ env.AI_SUGGESTION }}"'"
=======
                        "collapsible": false,
                        "widgets": [
                          {
                            "textParagraph": {
                              "text": "Based on the logs and test results, I would recommend a <b>rolling update</b> deployment strategy."
                            }
                          }
                        ]
                      },
                      {
                        "header": "📋 Reasoning",
                        "widgets": [
                          {
                            "textParagraph": {
                              "text": "1. The patch was applied with <i>no expected downtime</i>.<br>2. <b>All tests passed</b>, indicating no major issues."
                            }
                          }
                        ]
                      },
                      {
                        "header": "✅ Why Rolling Update",
                        "widgets": [
                          {
                            "textParagraph": {
                              "text": "• Updates instances one by one<br>• Zero downtime for users<br>• Easy rollback if needed"
>>>>>>> 95e4d276ba155bbc84c30c3a966784313d49847e
                            }
                          }
                        ]
                      }
                    ]
                  }
                }
              ]
            }'


<<<<<<< HEAD


=======
>>>>>>> 95e4d276ba155bbc84c30c3a966784313d49847e
